file/urls.py
from django.urls import path

from . import views

app_name = 'file'
urlpatterns = [
    path('upload/', views.UploadFileView.as_view(), name='upfile'),
    path('', views.file_list, name='file_list'),
    path('<int:pk>/', views.delete_file, name='delete_file'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('polls/', include('polls.urls')),
    path('file/', include('file.urls')),
    path('', include('file.urls')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

file/models.py
from django.db import models

# Create your models here.
class file(models.Model):
    title = models.CharField(max_length=100)
    file = models.FileField(upload_to='books/file/')

    def __str__(self):
        return self.title

    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)

file/forms.py
from django import forms

from .models import file


class fileForm(forms.ModelForm):
    class Meta:
        model = file
        fields = ('title', 'file')

file/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .forms import fileForm
from django.views.generic import TemplateView, ListView, CreateView
from .models import file

# Create your views here.
def upload_file(request):
    if request.method == 'POST':
        form = fileForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('upload_file')
    else:
        form = fileForm()
    return render(request, 'file/upload_book.html', {
        'form': form
    })

class UploadFileView(CreateView):
    model = file
    form_class = fileForm
    success_url = reverse_lazy('file:file_list')
    template_name = 'file/upload_book.html'

def file_list(request):
    files = file.objects.all()
    return render(request, 'file/file_list.html', {
        'files': files
    })

def delete_file(request, pk):
    if request.method == 'POST':
        sfile = file.objects.get(pk=pk)
        sfile.delete()
    url = reverse_lazy('file:file_list')
    return redirect(url)

file/templates/file/file_list.html
{% block content %}
  {% block content_header %}
    <h2>简单文件分享系统</h2>
    <p>
      <a href="{% url 'file:upfile' %}" class="btn btn-primary">上传文件</a>
    </p>
  {% endblock %}
  <table class="table mb-0">
    <thead>
      <tr>

        <th>序号</th>
        <th>标题</th>
        <th>下载</th>
        <th>删除</th>
      </tr>
    </thead>
    <tbody>
      {% for file in files %}
        <tr>
          <td>{{ file.pk }}</td>
          <td>{{ file.title }}</td>
          <td>
            <a href="{{ file.file.url }}" class="btn btn-primary btn-sm" target="_blank">
              下载文件
            </a>
          </td>
          <td>
            <form method="post" action="{% url 'file:delete_file' file.pk %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger btn-sm">删除</button>
            </form>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  
{% endblock %}

file/templates/file/upload.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">logout</a></p>
   <h2>Upload</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="document">
    <button type="submit">Upload file</button>
  </form>
  {% if url %}
    <p>Uploaded file: <a href="{{ url }}">{{ url }}</a></p>
  {% endif %}
{% else %}
  <p>You are not logged in. <a href="{% url 'login' %}">Login</a> here.</p>
  <p>New User? <a href="{% url 'signup' %}">Sign Up</a> here.</p>
  {% endif %}
 
{% endblock %}

file/templates/file/upload_book.html
{% load crispy_forms_tags %}

{% block content %}
 <h2>上传文件</h2>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form|crispy }}
  <button type="submit" class="btn btn-primary">上传已经选择的文件</button>
</form>

{% endblock %}